### ISSUE TITLE
✨feat : test-todo-app 개발

### ISSUE THREAD

**Issue by DONG-8** [DONG-8/Learning-Labs#7]
## 🤷 구현할 기능
- todo List를 통한 test 심화 학습
## 🔨 상세 작업 내용

- [x] TDD 기반 명세 설계
- [x] 비동기 작업을 위한 msw 설정
- [x] userAction에 따른 테스트 진행

## ⚙️ 구현방법 및 예상 동작

- TDD 기반 초기 test 설계를 통한 Fail
- 기능 개발
- test Pass

## 📄 참고 사항
- 해당사항 없음
